name: Build C Program

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt update && sudo apt install -y gcc

      - name: Compile Program
        run: gcc main.c -o app

      - name: Run Program
        run: ./app